package mldsa65

import (
	"bytes"
	"crypto"
	"crypto/rand"
	"crypto/x509/pkix"
	"encoding/asn1"
	"encoding/pem"
	"fmt"
	"testing"
)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Tests                                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

var testcases = []struct {
	name string
	pem  string
	check func (crypto.Signer, error)(error)
}{
	{
		name: "Expanded Format RFC 9881",
		pem:  expanded_format_rfc,
		check: checkOk,
	},
	{
		name: "Expanded Format Cloudflare Circl",
		pem:  expanded_format_cf,
		check: checkOk,
	},
	{
		name: "Seed Format RFC 9881",
		pem:  seed_format_rfc,
		check: checkOk,
	},
	{
		name: "Both Format RFC 9881",
		pem:  both_format_rfc,
		check: checkOk,
	},
	{
		name: "Both Format With Incompatible Keys RFC 9881",
		pem:  both_format_wrong_keys_rfc,
		check: checkBothFail,
	},
}

func TestUnmarshal(t *testing.T) {
	t.Parallel()

	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			// Parse the PEM file
			packedSk, err := unpackKey(tc.pem)
			if err != nil {
				t.Fatal(err)
			}

			// Unmarshal the private key
			var sk PrivateKey
			err = sk.UnmarshalBinary(packedSk)

			// Run the check function
			err = tc.check(&sk, err)
			if err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestUnmarshallFromBinary(t *testing.T) {
	t.Parallel()

	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			// Parse the PEM file
			packedSk, err := unpackKey(tc.pem)
			if err != nil {
				t.Fatal(err)
			}

			// Unmarshal the private key
			scheme := Scheme()
			sk, err := scheme.UnmarshalBinaryPrivateKey(packedSk)

			// Run the check function
			err = tc.check(sk, err)
			if err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestTLSIdentifer(t *testing.T) {
	sch := scheme{}
	if sch.TLSIdentifier() != 0x0905 {
		t.Fatal("mldsa65: Invalid TLS code point")
	}
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Helper functions and structures                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

type pkcs8 struct {
	Version    int
	Algo       pkix.AlgorithmIdentifier
	PrivateKey []byte
}

func unpackKey(pemKey string) ([]byte, error) {
	// Parse the PEM string
	pemData, _ := pem.Decode([]byte(pemKey))

	// Obtain the pkcs8 private key structure
	var privKey pkcs8
	_, err := asn1.Unmarshal(pemData.Bytes, &privKey)
	if err != nil {
		return nil, err
	}

	// Obtain the packed private key
	var packedSk asn1.RawValue
	_, err = asn1.Unmarshal(privKey.PrivateKey, &packedSk)
	
	return packedSk.Bytes, err
}

func unmarshalKey(packedSk []byte) (*PrivateKey, error) {
	// Unmarshal the private key
	var sk PrivateKey
	err := sk.UnmarshalBinary(packedSk)

	return &sk, err
}

func checkOk(sk crypto.Signer, err error) error {
	// Check that the key was unmarshalled without errors
	if err != nil {
		return err
	}

	// Test signing and verifying a message
	switch pk := sk.Public().(type) {
	case *PublicKey:
		// Test that sk is not nil
		if bytes.Equal(pk.Bytes(), make([]byte, PublicKeySize)) {
			return fmt.Errorf("Error: could not unmarshal public key")
		}

		msg := []byte{0xde, 0xad, 0xbe, 0xef}
		sig, err := sk.Sign(rand.Reader, msg, crypto.Hash(0))
		if err != nil || !Verify(pk, msg, nil, sig) {
			return fmt.Errorf("Error: unmarshalled private key could not sign a message")
		}
	default:
		return fmt.Errorf("Error: could not derive the public key")
	}

	return nil
}

func checkBothFail(sk crypto.Signer, err error) (error) {
	// Check that when the seed and expanded keys are not the same, an error is raised
	if err == nil || err.Error() != "error: incompatible seed and key values" {
		return fmt.Errorf("Unexpected Error: %s", err)
	}

	return nil
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Sample data                                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

const seed_format_rfc = `
-----BEGIN PRIVATE KEY-----
MDQCAQAwCwYJYIZIAWUDBAMRBCKAIAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZ
GhscHR4f
-----END PRIVATE KEY-----`

const expanded_format_rfc = `
-----BEGIN PRIVATE KEY-----
MIIP2AIBADALBglghkgBZQMEAxIEgg/EBIIPwEhoPZGXjjHrPd24sEc0gtK4il9i
WUn9j1ilYeaWvUwn2FP6abgZkCPozWeN2fq/kEdkb/0Ms8x/eVgFpx5w0jcbBWPj
zTNGFJyMnrzyOwpOWpAO6pxlYnkKfGPjhmPaot3bbkgNxAWh5wGUi3SEHvXMHD8r
8yeXLpUQUQzVN17MCFVxdxGHIiGGI4EABCR3gGFHUAdQFxcDVQRRUSVHGDgEYXVy
IkQQiGhghkYBJ0dWcYCHBmaGQzJEQSIENjhmdQKCNjQkQyIFc2QQZFVUdyJ1VoFD
NhRiVQggZDdoVGh1Q1N1EGhxgzOAVHUFJYB1KBiEOBEIcmAgIAhYgwGDYROCghIG
FxFXh2h4iHhkN1RgFlcVUIRxiGYHJzKIBmR0GFZ2IYAxgnZkFXgkUCVkZkMRNQQ2
R4ASZnMUMBFmBlWGRxg2iGNQOEeGEQEgI1YRYTeGB4UyEkAHVHiCMENmYRZgQlVB
goVgU2d4VjhDRDBjJhB3BzF4QnIUERZTA4UnaGdGAVCCNzUyB2YQdQRoEkgGZgMD
JlIxJEVAiAAxgIh2chcwcYJHIVEngBFlRHSGYXIjM4CGYGRGg1IVhCA2gBGAIRgY
MxdzVFNIgQBEhlNnQ3BXcliDNGA4QjKFaBAGBCYEJYRWAjVoIFGDhjhDJCEiQkVk
WFhncUVyhQR4hxcYBhiDYIaGQVZQgRZQJkZwBggmYic4MXJAclcwBycohiBmdYho
JgcGQCAzA0NmMVVGQkU0VmcYc0Vlg3AiUIRoViiAcDZwhGI3FxAGVxdYR3hwhlVT
eCI1FEZ3KFZzAyKHABQzIGFxWEVSZjJQJlEzR3c4A1UWQxNHNRBmJ1F1dAJGiIFw
Z0NGgYYBdlJFMzCHIQQ0NAEDIodjUVUmUIEwd0VEQWgVQYNjZBEgQCaHMENndxKA
iEY1VFMAYkWBBFg2USSEJ4A0UWZjWEN4VgFGURV0IyFDZoUiR3cxNFAXg2JCBVAA
ZIRHEjRAiABgRzVAV4MzYwghBhUiUgckiFE0hjcGdiJYhXEmVnNHaBZGRoQlhwgS
JwVQCDgyACMggGY0UzYAM0aFckcGNVQANXcSJ1IwcUJTaHQ3RXAFZkMiRIKFIHIY
MzAgUzczQHcngFUlMGNSUEBnM0YTGAcoBxckg3djRXMYWFFgIzNENiUWQzgWCFh3
NGJCiDAHA2WFN1UAdVIxUDcCEyRjBDcIaAY2FQMDAENYY1cIAhEGZHNGNSJiAzBD
gCEIUodXgyEHiGdICFY0dDZzQoQFhGaEFDcAVRCHNCZEdyESc4RzZSZHJXcURwQX
hkQmAkcRh0CBIhZgWEcXgTcGdoCBcFgYVYVHE2NCEHVYAWNYNYUYRAOEcRAzh0Ji
gkd0E2VUQnBzRjV3dQBmJWJoQgISRoOGRhZkYDEiU4iEVACEVzRGR1RHJWBUYWaE
ZjCIBjgnFWMocYOEBlIkdoEWBmITAzAYaAKAE4RjBQVlcjh1g2VyMjBogEYSJgZl
FnVXBTJBMidnNRcIAVMAFihGATSIdwERiBVXExVGQxFwRzKIKFY2gjRVUEGGJ2Vj
ERFodQUQQlRBRCeFIhEXF4gVNoUVdEcWYlU2VYNjAlAoVXaHUycTcQNyNwVxR2Fx
NlGEEkI2ZERmQUNSBSEIUVcDM2OGAlhCZigUgRBUYmgXMDh1ZDMhZYhWhmNjKBNA
YlQBIECIZUeIYXFldiNyYjSGcDARURVjIFB1NQISIQhCZTFDVWcRFSVyAQaFNjAV
BVdYYFh4QxQxMnh4gIc4R4hjeIGBOHNCYXg4hSRmdzNQYCEVFGQjgjJoATVEB4NH
U4VTV1KDIzUYdgEVITQyV3MzNlUYhhWBYWgkGEIhIjCEFEgVEgEQMCR3ckJUQ2YG
dxdwdgMBRSVANQAYOHMjdzUmUIY1cRNzRIFgUndFZVNzAIWDd4UDUSERVIBiiFAY
AmgThlIFNGgBMgckGAMhMAVyOGQHZCcRQQGDhSVRBjJgcQSGUXaDOChXJ2I1RRhz
UIMTKIY3ZmFCYxFnUDMRJVN2QXYDFDMXchIjRBioLk9cnqD6+Z6wTXinMycREXwz
8Y7KIfh0M3atpSGYBKftmlVX/NZ6NVCzpLjFiGKcAhR1+j1W1dbPuxoJvajRTeYi
3f8W2LyZsUJ4qK8ddr7RV2ct2cMjFvl+jare+NnaaVhnJVZ/uWtZmQ1L8LycGVuQ
t0KV9WdbJCV8JxDBdbAVPykRMowut6u5rUbnCotTw56mQs7ks8tCYg6GPOi2UM6K
3NkjchoWhwI8ZzqMu2sD1RzRl+jDRuutzpOVD4jO4gHbnjIIQ+KfMA2aGVANcKTK
8nLGnk7vafu4pV79fKK+2ZDS07WChI+cRcKrxUz8R9NPBsD/pW/Ndiq5y6kUbXcl
IYljskDXK20iyTFx+9R3iLducgQt7wh40j32MaGh5aYCdobeW0oQ6RBpyPK6Almw
TWQJ2pZWfKUtpJcCblg6Ds78HwHmuYjiH5dnorfhZy3rmh4qP8yGOqkVF8M0YgYB
tP55cw6TSTX0tvvE4yaVFFwrX2oSf+zAondFHrw/1SNET57nycNFNPNW21RPwxwb
/eX2XHfqL3wurkxV668QQnHFZv1OusccemLHSVKBeuZ1UE2VmbG3YrasoWioMkjJ
2a2wzrFVbldZSQu8DHkAeVrXISMDi2YvZPEGqZk2gaJdWa97yXojW+koTFvEWmyQ
yxwpmcZj2WtHjiMH+FVIlX1ldA4mc+nr0TUoKQOPRiuP07VoHaVcAlJSOFNSXqCt
ZH5xrCxaiJPmA6yX5WwEzrLyb1xbS22Uq4ETgP0A8iCP6GU1CGrr/TXCkSBiTAT7
thE5KdnFVjUCU3ZsIJ/bqDyV/M00KigJk1XQC8hj9O71lusLQuvMfHlJHM6uIF6g
uAWfu4pXJsWUnSsV5+KcUfybAu4aT8NXtfG++cSt1GoqkgwvvwijfrFRS/oVEQpD
kqdMbxPFDFz/2XUxCY180jtg6zXEpCi0bFU4bhAQxLp/cOTH7LdXXzBjpx6E39zw
mliyzbD5nyftN4YQ0ly617+mug1ZGJz+iOq5tG1+bbAwfqvkGY6ZvXH3eatmWB4J
Evx7HSWFJF6aEmh6l1zV6OHcwEXV+JHExoXbB8+B53OJs2Pra9/jmyf/hMl+7+4W
LjtFH+aRRxnLZDbYVZYP+RXXzqat6v38HAV4bEn5I6R0/9/DFToG5u0LCtIg1yUk
Q01Sc8Cqtt3k6RR21YGiaVpg3m2fRNd6oIJm6TjutKlZfJtkmGBZ5JJipOqyRU4U
AVrQU2xCczpdd9eZXCogRGAJ6/5WMsgMCO0rl681BmSJ9ZfrGx8R8E9g4MkEAVnE
SrPmDgoVIp0ZEii+0Xu8Osk5s8Z87hNfNSwnIWycMfcqPocEDF9hkwbrC2zKKpzn
sioWlNAMqcBeMVEmRX8mzoT5YXJBhgeC+GS0c9hAF0kZArG9yM3FgA3UYSf7gKcc
CVtHOlYlKbOx5+Q34Vil9mZumXTQBbBiwjCebc6Y+bZYxuP5ohbVjIyRQr0cjIWp
2ocuu/rT/qnZq6K2jA6PGcb/XwBYTUXa+dbJ1p7QS42o1ocli3eAeSdhLFMERv6n
aXrj+SZpiSm8alqM8+ICTA8MXuV7WGm/mBiByvnjZl/H9+/GeJKfh6VuqkLqTR/2
aRgi3XmkcJa3dtHY8BRW5Yc7BzhAbDgsVzrpzeLZ5/IxtsxcZ2589DljNzATpYB1
OB/wlJvghFRtcuT4o+X+SqUJGt0jTir+ADCxtmOunS0yQQmGuUAqqvJGW3Sl4tC8
OOOpK73dih/te5SMI8zm+MCP41aDW6ZbD5hAaGFu9IE479ib81elTS6783bL3Mac
Xx9hxk0nlLwGzLmr32biUIXYyDDirjsP4PB6evi5MgvzQpcJl9Z9fBJZOo+/reY1
qsUwg6cCLEfV93pStXtZjak5KubYavxG/AZFUYG5x1pkbcIfgeS/ITdT3nN/0qFA
AnkgrdNaIj+fX0RlzrYMA+0EVaMzpcyDrb9D8fQsLMuDKMIcerf67Sshz63i2lUi
Oqqyr5tBxzMjQXRjQbOaovQ4FWUPVIBRFCTPppAXecTRi2OMwCh6qvMWgDONILF8
dEn9xqJ4qNlqgu5MTspAEl4tZSkAcceu8b5qmRWY+51ZUSUjvNSzjFZrjoCnOuMz
4TRBQyfvHYPEfEnf55Nt8TOKXiR3h4aPyE/cuVrInBhcS7X9V7IzisQrQcEKgj3z
liTzaxWi8GdYTgbKLgjMr/Fhj+Ad0G3zUS4Lck3shQbaJCFayswsUbgq2NMCAC+0
EGix2k+LsUeYezUWutXb3fATGP0/qbxDcCrEmMcZ2V8uhBtiKl5ISKPFwmKVmZLq
en1yyoo2gCj0l9+tkzVcuxu5eG0U/yz1kDF4SPlYVkJxEN2jb1GSqBbOnIgWzHu/
yATvxACFo4ULifHn/lZW26QQ+QapfDIzbBrn6Bc3qD4Ic1TkKNqFONlI2/XfrLWd
0rX9O8gD9LpDLJpznfLPqe2UhDIPl+3/GkjGuGswAs+3ct1eVivEw9aD7ZZLYZn6
BRSweQ2VgJW3uFxr6HX7tVnhkwFGzOpjo4ihlP4Jw96gO+Ut4n6QEBev6AmvYwpz
gr9cTNTRuPQVeftDSO3kygX0zT8TmjGyVE5Rbb5Ahrm7SyvtR+LSMJgt1RkkKdN3
t8B0XMBo4vWkqgTH/4cgntElmXag/Jsl6ehR1ONQLALIXW3/Ap4hHQHr8OnnGI1W
j4Q32BOw8SLy+xdgO2k+2cOPF8/VC4FebZ38DtLM8Z9jmSdKFCDyNaWdi/ckNF4U
5F2eS+iTTfw/qSZ422HXEYv1PLiiIlszX36uUOP5QSN2KNt22Oo493pyrzomyB/k
NSOzNVNaXR23w480EIK7VzTQieiuMJz9o6C8tc1bCXETyO35YWqk9uZjG5ElJ2+z
9oCjQ0HD22aNxsrUX8k7JwjKKvdczOc0/RkcUAidrVOYL92uAlMf+T4fIf85X8Ch
KHTt8GtvlkfpWnMkWGxx39kdkB1iGFgZD+zQDM0RC7rFn5bLiEw8k5lHSKVvQSg7
/EH7iQUhU6iUWIw8uQF/PWYybJhWN+V1rLgSNGNCZUAl1gLeO6lAwZrBpjPf/al3
tSm4AT4ZwdbQaA9NrmLJJEUK5mqrgvIUcwYdqz1iskf5B+NVGTmtP1Rl6dCKgr/q
F+6htrK5I3V0d/mTAAsvQ7cPKKqrH+miatH9M2FhbAsOJC/nZgS3AzofMOl+KPUm
yjyID+K42dGwyf8YizHLnZdCWsq5shbZimrjVeWD2nHohk7j0WsHWXlhkO9UXB5i
v++Sr2yhR7EyRNbIkvyO8iOrP0P5JML0Zgl+6A==
-----END PRIVATE KEY-----
`
const expanded_format_cf = `
-----BEGIN PRIVATE KEY-----
MIIP2AIBADALBglghkgBZQMEAxIEgg/EBIIPwOn8FevIq0TRBFiPoICGc5wQurFu
RFyi0fvivJ3bwQ7EEU3tgFQCDH+0gORxSG+prvxmFW1zUe24vTAJiIqGU303dMsJ
1YEgJjhTOtnj8rEWdykmwrJOj3UC2GQFGetXcsrAkUaEb4WVd4W6uHW9aIJvb0re
XFuXygr7Jez3HHQOgjVjQheCQ1JWckSCCFSHKBhxgFU3RiCIJGNlAyAwZCAXRQJB
RoECRxNIYTAREwcjOEdHFlhBVSggA3RURyJ4hQZGZygABCVVRBWER1V1ZFdkQzMY
BGA2IxMFKDU4QTFRADcGcnNgglUgYgSEaDR1AXBwICFRA2dFhWd3YWAVEndSdghl
BFQVdzNEg2UzAwdmFwBXVTcEUUhVc0KBcQZEYHIVEQVUdEQQVmhFcgAmUgEIBDFl
YBFHNDNGAWETVUghAgEXEwcGYjd0YzRFBGVxWAQRJ3M0ZoGBECZgZjMlIiBwJGVY
g2cCEYMDcjVVUAJYElU1NCh3gTF2gHUQRHRidoRGU3AFckIEWBNXARODQncYQldH
hggiEGdEdmRFVhgzEHcVNIFIBIE2VwVHJydQOHFwJwWGMYJVhGgHNARHNDJoNQRR
djBlg2VSh2NGJnVHZVFSNggEBnBoURRFJkIUUGMyZ4NCQ0EAEwQEhkUWYzhTeHYF
R3KHUQhYiGVDgjIhgREnKCUgYYJQWAJkYoVocVdXIDVUJBdnGEQEJ3gQAyFyIBIS
d4cUIgVkRyN4dRNWd0SEUlhxIEgGNWcmMIOCRQc1FzIyRyZEh4RFdFeAGFKDdliD
Q1AVV1YXgjNVYBZoh3MTNwglA1cTEQFXRVByUhMjeHEXVHQXc4gnBoFihwKDiBhQ
BkdASEAzUlNmSIdnBYJjMFYkdHJld2iEAGiHVjFEQ3NHWBUyWIQQUgImJkQzSFcQ
RnchdUEkgDBoMoZQYgZRdQBgchV4gSaBY1czVHNlRQCHJ1AFiFExUocCUUh1NHIV
EwcHWDNCVVKEICA0VAFxdSIjVgBDdoYhQnhDYUZnVEhhdFdGeFVhFwYDZnhAQEh4
BQI4IDYRhDZDhkhzJRMiIHh3goI1OHUlJHZHgwFiMjNkVwiIYSAidiYxZiERgkAw
QHMyFwBSOAAEgoclYlGBQgBjYoVAI0AzBydlVgEyRSMWA3VSEENYIQcXNIEABjBU
aGcFOHhxgDMjSFFEdjBmcCM4KGJYIlUUVjhFZWMYBISBJyaGVXUyeCg2RzhCIgOF
VXFQUQaGBWeHgIZBEwJBcXEHKIAFV2GABCB2F0gkUSSGY2dWMmVAaIMCgUAmIkQh
BCNVBFUzFYNCZ0GDBSCAVAVTUCF4hXMRhDdRc4NAMoJVdjUTJFhVIyg3VkcYN3SH
g3BXeGYgQHBlFDNBAyUEhocmBHh0FBRzNxZWVzBDVhMYc4BjEgQzJFEgV3cEhjUE
GACHZ3CHUkhwQFYgFzQ2JBcohBRCQFFlIVIIFgF0U1FEJFg1eDMxEgiFQVCHUxMG
IVRic3JAZwJ0gTJIBFcQgTgoZyADRQFYY1dxQ3SFBiJGEUYTFQAnUnUncgEogCdB
RXVmJkMGiGFHJXR3EVRFRFNIgIdTQ4ZYAwdyMxgyQGdQcSgkdTFVBkURdicoAGNG
FAMVA0ZxI4R2dVQGhzeIGFUVEmdoQHFUUVBngBFxIzWHITR4hWNnJjcWUhV2SEM3
EodRYUVohjQhcEeHYRNiNjEkFwRyQENDJnOCB2BEZBZjdCRkN4OBJmd3g0FxBhdh
dGcUhiAwM3UXNmVlImGBKCdIUARmMwKGWFVwExhnAoUjQEgihQMAYgQkI0ZXcngQ
SHQTBRA4ZhgDZSgiJxBoYGJSU0h0MhFoJXhVIWJxZURSg4FwghgQZ2AHIGgoJgdE
YBYGAzAoQkIgggZmNSIlVRYYNHaGCIcDcigxJoEAUDKDNhCBNEKEdnhQYjABA1VG
R2h4UIZCYiJ3AAgEJxNwIFRxYmcCcERGRiUUQWUFgiVSJnODUiSGcheHZSJ0gTh2
ZRAwdohGcTKBIFYBZhU0A1ZFgTGEdTMkdVNCM02Np4yVQK3cpw9yuAE9TAOc4q0G
h7S5UWcqGQGc6H6AK4pf30miT64LSRJR/U0q6MhP3aPp6YlVxWasinptFj7NTxqw
fcjrd8puqBSZ8CwTFD+bBdTL3wwhysvDx8AlapJTKr1PVNzKMZtCZgAUNmmu/7T1
xHxR1h8bC90Uf6b0Rc4vck4iQTCSYH+lDvxkgxn9VCJQoEx21FM9ULa+5rmex5i2
cdk+BLRa9+hCc09QJxkqwVjVqNdpBbOKOZXo5Ra3udN5KqpsgkLnxq3wT1o7ZDDJ
Y7j+1rDCsvny4KXligC9F7Q+FxJfcCPl8jHLD3I1RgqrSugFNV3D96OjrXtfRZgX
voymeRH6mzDOmV7C8aaOAObb96ecHWDQ3fknWo1VIxiWcvBa2jh9SQNvpwSbe19S
Ls2E0MdcO02ojvpPdaxZJwHwMNfYzIBLPWOYyrHrNzduYUANjN4gpMTdsAs5WfV7
r51rKlRFflcWLUl3uqzxtiTznaWLxBAVHxReK+E3LkAkG3dd3jLdTzGQH2vDpR6f
3faRkOouhRM4g1qMbpf+YgNX/6R13rbL3rseSr3jja38Qi3yq+vQe3kNh7po3kqk
gmcLClwLCHHhDS5oO0CcMCwx6hK3DiYjyZ6T7a/IukCRXRvOAekLRKDfutD2HlgP
ef/wNy4gFdmgatNnJimrKrvLSgTKUblBxU4XyUVzwzLArOPgdqilthz0uZqZzpZe
aHajGMrAcOn/aqC7qVD+GQuBLbai/XYsKnYvg7bnzbXJ/3NYqF4vNEZw+kpqPNj2
7vcUi9eWFMnDHbEhuZNS1o++TTUaiFgR9xcOIP7sfyDdWRpLWuqb/yGZdLt/Gcxb
hvGw6amFKvYhEHT7UEbQJBRcnUc9gY6IvqK+1VwMKId3OsUdvwNgOpvY9VSSQakG
yo9mRI09VVxYZOKTpoYXiCCDoAD/ymzFx8VJziNw3VK5KFyNwkkr26PZc4uVOcDd
1llNMhOP5FLNJt/GmAOIuzKJXMQDR+3sapU59jVJxt5fK1ISc5TOUz54WzaUKLag
gbnRtsTcDm/QL1SkOukP2sFEvG19iH/ilOOfvgH1rRKAI2jTSz15/Gm1KUnCrDFV
P09lTu+D+//fUftY8kKQaRhHVYYkosP0IYo5hsJU7M6cFfpV2g1ZCi2Rg+zWYinj
QAAysK3pb/akc4ba2FZCyVExzSIQGscCJz8F9btsPnvZogkHHV/RoSg9PYdnjp/o
NKbIDbaaymyrhDPu9XL+IuRuWsMJ3cp5ZizqUkFhyiYx9wC98j7gnrq6TUP6y/x5
yAtjVdr+v3rfiycMi5N9D+3d/VuqSxPKhoN1tLzaW/xOBVbXY1g/felOVsqgD+lh
sdMgx9NSlsjVFQwuLZQUVTVTGHuS+xVAfy8lqwTRHw4Ws2h4duJLck7rkJZiijFH
BeXnwJeCTq8D2xcgCLTTSc+DVjacf/kDDUhfOHfq8hvAZsd5/Eh6nA63YBdOa7wa
LZow81jVJeJdUa501Kw0Ef5qHs5lrXHjVLHNWEHmu2HQdyEYHh0jzXUbYpLCzRwp
weoCa8bys5Oho46Xhr1t1oYYYhTJ7igyRFsN5lK55DuEs/H9O2I9UAcj1wQjgzUg
TZpwoPR4Vb97vMDwlWIZLgKCdQZCB7Puf800wxhecpzLdTPX+eudFc9h17qXdVEa
QMxTXJH8Eeb65XanS74Dl3fEfcZ3fNZqJrYmD/tZm/Qx2OgSdSo2FdzpaUIaziwS
InSmauuABiRnM+/vwhcPqN7P6+IMR0yJb5K6i6FiXboLuiJ2ozmNUd8C33e9dohY
8aK43R099rPzkceYOx2HHadSLL/RmAS2xbYSK6UOw7eLvX8yU662k38bYTmM/Yuc
dnZytnSEEK1zVWzOeQ+yXuyWi4hbbVNOZPeWHMQlBsHg01lCGOO7xSzMOEQ5Kpxp
sky+oYjOskqySMJKg8ZIqjvw7Onf7CYXvoONdTAu+JsZL3bGaU/jSroiJDCgJyMn
i0wu9gY9md8DYN85cirjmit2F3mluCVU7RBad1Ki5qht3YYzLaLHOZljpDsi+p3v
E/jjR0xR4I1j24H1vJR0dw0L9qVj4IXqiynHAgfviQkB4lKWNwzx0ec10j75L+sp
cAoVMsNNKPEYKly6X+arV7jQTxOpnM/bsxqVb6Z0OgX2UOWbkg4/qZIrwiPpUGsy
98pX3DhazmAWPxnQJQ9mO1IrTwWh9CBwVHr4TWPtvPYgowjTRvpFd5e6zfiCeh/u
hWp6Tioo8YxNkXjiYMe9K0hiJ6Z6wXFFZ5pHWeqBUPzv0yigCU6tzvKitMQx8wkJ
xeLt/fnfwGlFgrMfpsRTXNrv+2LDsVlEVpXj5i8ZfsLUb5toryx9jIUiGhKiIHt5
RjICBZn1pTGuAkXgQX5L50MiaHim+37+khdPPUGy+FaXWHp5x72q3rpjKSTG4/sc
thk81pMOTeAeTSz8Jpvm+RW8adlKkB8HDhjioa5O5ZfVAfHZbEZVNNLjKObXQ7w9
67NZLfWH/PS2O4FI2VMEr4POeG7H8WNdh2rFddOnUq0m6tNbo+XQjeiAWNFWgiMN
ZMjf0xeCNNancqO9bpmCba/RP6AL6tkpFtWz1tYbPOH7QtPrSAqzeo+2EUb737Z4
zjckQdRrEhLs00kEFQfIi7hirrWOv519Ar0lJIgCKtTVdQSEu4OSy1HOk6OQfVu6
+x+nC2Z3iHsfPssZyDoiiu1y+zcXr6/8ZfOXN9yhwPpN96MW4je7/3KqdzgYLp4y
M7D3pZVmh72sf7ka1LQ5RgIuondR6p6XzIpOJ+HeQab2xiLV8yHi6imLgXXp7aHi
xOA8rxb23WTzJNFITGoPdjE4fwuVjmnUkRmparAkUj/5zzq2H12CIZtJGEZY3Vhk
zCINCEJND/klTM506LzBstf3ZrerTimtEyG/h8R4tOFcBbpWHKiLsPG829GBobQ6
TpcFTu+LL43TyRs/DQGhdJ3FTCH8KTKtlP8GPu9lPeZKBSAhRDw/1oD7HIX+/p6s
lHSDQJWio7Fj3k3wf7ZONgZsN2yClgqpZMeurKA+T5je99GoIJdX5S3B0OJjpOmz
gtjFAs0a1eZkhqTSRYhqtiwr8OOSoubrXulqUV+8tNk3LYkh7tZLX+GxZosbJj09
aARYhxQdLKR1ULMsbdPBZndimWRH3me9+bnhb31l6yOm+ePfVfpzLAnTcBuuKLwW
EfPxX3BeycJzeU/4nL5Cb0GAVsnTqN5mh5ErEfWQXm54oocMckBqHJijN9Z+2Vrw
GgkU5Uvnurkz1JqrxjUJ88J7HIpnXR1fYnqGxA==
-----END PRIVATE KEY-----
`

const both_format_rfc = `
-----BEGIN PRIVATE KEY-----
MIIP/gIBADALBglghkgBZQMEAxIEgg/qMIIP5gQgAAECAwQFBgcICQoLDA0ODxAR
EhMUFRYXGBkaGxwdHh8Egg/ASGg9kZeOMes93biwRzSC0riKX2JZSf2PWKVh5pa9
TCfYU/ppuBmQI+jNZ43Z+r+QR2Rv/QyzzH95WAWnHnDSNxsFY+PNM0YUnIyevPI7
Ck5akA7qnGVieQp8Y+OGY9qi3dtuSA3EBaHnAZSLdIQe9cwcPyvzJ5culRBRDNU3
XswIVXF3EYciIYYjgQAEJHeAYUdQB1AXFwNVBFFRJUcYOARhdXIiRBCIaGCGRgEn
R1ZxgIcGZoZDMkRBIgQ2OGZ1AoI2NCRDIgVzZBBkVVR3InVWgUM2FGJVCCBkN2hU
aHVDU3UQaHGDM4BUdQUlgHUoGIQ4EQhyYCAgCFiDAYNhE4KCEgYXEVeHaHiIeGQ3
VGAWVxVQhHGIZgcnMogGZHQYVnYhgDGCdmQVeCRQJWRmQxE1BDZHgBJmcxQwEWYG
VYZHGDaIY1A4R4YRASAjVhFhN4YHhTISQAdUeIIwQ2ZhFmBCVUGChWBTZ3hWOENE
MGMmEHcHMXhCchQRFlMDhSdoZ0YBUII3NTIHZhB1BGgSSAZmAwMmUjEkRUCIADGA
iHZyFzBxgkchUSeAEWVEdIZhciMzgIZgZEaDUhWEIDaAEYAhGBgzF3NUU0iBAESG
U2dDcFdyWIM0YDhCMoVoEAYEJgQlhFYCNWggUYOGOEMkISJCRWRYWGdxRXKFBHiH
FxgGGINghoZBVlCBFlAmRnAGCCZiJzgxckByVzAHJyiGIGZ1iGgmBwZAIDMDQ2Yx
VUZCRTRWZxhzRWWDcCJQhGhWKIBwNnCEYjcXEAZXF1hHeHCGVVN4IjUURncoVnMD
IocAFDMgYXFYRVJmMlAmUTNHdzgDVRZDE0c1EGYnUXV0AkaIgXBnQ0aBhgF2UkUz
MIchBDQ0AQMih2NRVSZQgTB3RURBaBVBg2NkESBAJocwQ2d3EoCIRjVUUwBiRYEE
WDZRJIQngDRRZmNYQ3hWAUZRFXQjIUNmhSJHdzE0UBeDYkIFUABkhEcSNECIAGBH
NUBXgzNjCCEGFSJSBySIUTSGNwZ2IliFcSZWc0doFkZGhCWHCBInBVAIODIAIyCA
ZjRTNgAzRoVyRwY1VAA1dxInUjBxQlNodDdFcAVmQyJEgoUgchgzMCBTNzNAdyeA
VSUwY1JQQGczRhMYBygHFySDd2NFcxhYUWAjM0Q2JRZDOBYIWHc0YkKIMAcDZYU3
VQB1UjFQNwITJGMENwhoBjYVAwMAQ1hjVwgCEQZkc0Y1ImIDMEOAIQhSh1eDIQeI
Z0gIVjR0NnNChAWEZoQUNwBVEIc0JkR3IRJzhHNlJkcldxRHBBeGRCYCRxGHQIEi
FmBYRxeBNwZ2gIFwWBhVhUcTY0IQdVgBY1g1hRhEA4RxEDOHQmKCR3QTZVRCcHNG
NXd1AGYlYmhCAhJGg4ZGFmRgMSJTiIRUAIRXNEZHVEclYFRhZoRmMIgGOCcVYyhx
g4QGUiR2gRYGYhMDMBhoAoAThGMFBWVyOHWDZXIyMGiARhImBmUWdVcFMkEyJ2c1
FwgBUwAWKEYBNIh3ARGIFVcTFUZDEXBHMogoVjaCNFVQQYYnZWMREWh1BRBCVEFE
J4UiERcXiBU2hRV0RxZiVTZVg2MCUChVdodTJxNxA3I3BXFHYXE2UYQSQjZkRGZB
Q1IFIQhRVwMzY4YCWEJmKBSBEFRiaBcwOHVkMyFliFaGY2MoE0BiVAEgQIhlR4hh
cWV2I3JiNIZwMBFRFWMgUHU1AhIhCEJlMUNVZxEVJXIBBoU2MBUFV1hgWHhDFDEy
eHiAhzhHiGN4gYE4c0JheDiFJGZ3M1BgIRUUZCOCMmgBNUQHg0dThVNXUoMjNRh2
ARUhNDJXczM2VRiGFYFhaCQYQiEiMIQUSBUSARAwJHdyQlRDZgZ3F3B2AwFFJUA1
ABg4cyN3NSZQhjVxE3NEgWBSd0VlU3MAhYN3hQNRIRFUgGKIUBgCaBOGUgU0aAEy
ByQYAyEwBXI4ZAdkJxFBAYOFJVEGMmBxBIZRdoM4KFcnYjVFGHNQgxMohjdmYUJj
EWdQMxElU3ZBdgMUMxdyEiNEGKguT1yeoPr5nrBNeKczJxERfDPxjsoh+HQzdq2l
IZgEp+2aVVf81no1ULOkuMWIYpwCFHX6PVbV1s+7Ggm9qNFN5iLd/xbYvJmxQnio
rx12vtFXZy3ZwyMW+X6Nqt742dppWGclVn+5a1mZDUvwvJwZW5C3QpX1Z1skJXwn
EMF1sBU/KREyjC63q7mtRucKi1PDnqZCzuSzy0JiDoY86LZQzorc2SNyGhaHAjxn
Ooy7awPVHNGX6MNG663Ok5UPiM7iAdueMghD4p8wDZoZUA1wpMrycsaeTu9p+7il
Xv18or7ZkNLTtYKEj5xFwqvFTPxH008GwP+lb812KrnLqRRtdyUhiWOyQNcrbSLJ
MXH71HeIt25yBC3vCHjSPfYxoaHlpgJ2ht5bShDpEGnI8roCWbBNZAnallZ8pS2k
lwJuWDoOzvwfAea5iOIfl2eit+FnLeuaHio/zIY6qRUXwzRiBgG0/nlzDpNJNfS2
+8TjJpUUXCtfahJ/7MCid0UevD/VI0RPnufJw0U081bbVE/DHBv95fZcd+ovfC6u
TFXrrxBCccVm/U66xxx6YsdJUoF65nVQTZWZsbditqyhaKgySMnZrbDOsVVuV1lJ
C7wMeQB5WtchIwOLZi9k8QapmTaBol1Zr3vJeiNb6ShMW8RabJDLHCmZxmPZa0eO
Iwf4VUiVfWV0DiZz6evRNSgpA49GK4/TtWgdpVwCUlI4U1JeoK1kfnGsLFqIk+YD
rJflbATOsvJvXFtLbZSrgROA/QDyII/oZTUIauv9NcKRIGJMBPu2ETkp2cVWNQJT
dmwgn9uoPJX8zTQqKAmTVdALyGP07vWW6wtC68x8eUkczq4gXqC4BZ+7ilcmxZSd
KxXn4pxR/JsC7hpPw1e18b75xK3UaiqSDC+/CKN+sVFL+hURCkOSp0xvE8UMXP/Z
dTEJjXzSO2DrNcSkKLRsVThuEBDEun9w5Mfst1dfMGOnHoTf3PCaWLLNsPmfJ+03
hhDSXLrXv6a6DVkYnP6I6rm0bX5tsDB+q+QZjpm9cfd5q2ZYHgkS/HsdJYUkXpoS
aHqXXNXo4dzARdX4kcTGhdsHz4Hnc4mzY+tr3+ObJ/+EyX7v7hYuO0Uf5pFHGctk
NthVlg/5FdfOpq3q/fwcBXhsSfkjpHT/38MVOgbm7QsK0iDXJSRDTVJzwKq23eTp
FHbVgaJpWmDebZ9E13qggmbpOO60qVl8m2SYYFnkkmKk6rJFThQBWtBTbEJzOl13
15lcKiBEYAnr/lYyyAwI7SuXrzUGZIn1l+sbHxHwT2DgyQQBWcRKs+YOChUinRkS
KL7Re7w6yTmzxnzuE181LCchbJwx9yo+hwQMX2GTBusLbMoqnOeyKhaU0AypwF4x
USZFfybOhPlhckGGB4L4ZLRz2EAXSRkCsb3IzcWADdRhJ/uApxwJW0c6ViUps7Hn
5DfhWKX2Zm6ZdNAFsGLCMJ5tzpj5tljG4/miFtWMjJFCvRyMhanahy67+tP+qdmr
oraMDo8Zxv9fAFhNRdr51snWntBLjajWhyWLd4B5J2EsUwRG/qdpeuP5JmmJKbxq
Wozz4gJMDwxe5XtYab+YGIHK+eNmX8f378Z4kp+HpW6qQupNH/ZpGCLdeaRwlrd2
0djwFFblhzsHOEBsOCxXOunN4tnn8jG2zFxnbnz0OWM3MBOlgHU4H/CUm+CEVG1y
5Pij5f5KpQka3SNOKv4AMLG2Y66dLTJBCYa5QCqq8kZbdKXi0Lw446krvd2KH+17
lIwjzOb4wI/jVoNbplsPmEBoYW70gTjv2JvzV6VNLrvzdsvcxpxfH2HGTSeUvAbM
uavfZuJQhdjIMOKuOw/g8Hp6+LkyC/NClwmX1n18Elk6j7+t5jWqxTCDpwIsR9X3
elK1e1mNqTkq5thq/Eb8BkVRgbnHWmRtwh+B5L8hN1Pec3/SoUACeSCt01oiP59f
RGXOtgwD7QRVozOlzIOtv0Px9Cwsy4Mowhx6t/rtKyHPreLaVSI6qrKvm0HHMyNB
dGNBs5qi9DgVZQ9UgFEUJM+mkBd5xNGLY4zAKHqq8xaAM40gsXx0Sf3Gonio2WqC
7kxOykASXi1lKQBxx67xvmqZFZj7nVlRJSO81LOMVmuOgKc64zPhNEFDJ+8dg8R8
Sd/nk23xM4peJHeHho/IT9y5WsicGFxLtf1XsjOKxCtBwQqCPfOWJPNrFaLwZ1hO
BsouCMyv8WGP4B3QbfNRLgtyTeyFBtokIVrKzCxRuCrY0wIAL7QQaLHaT4uxR5h7
NRa61dvd8BMY/T+pvENwKsSYxxnZXy6EG2IqXkhIo8XCYpWZkup6fXLKijaAKPSX
362TNVy7G7l4bRT/LPWQMXhI+VhWQnEQ3aNvUZKoFs6ciBbMe7/IBO/EAIWjhQuJ
8ef+VlbbpBD5Bql8MjNsGufoFzeoPghzVOQo2oU42Ujb9d+stZ3Stf07yAP0ukMs
mnOd8s+p7ZSEMg+X7f8aSMa4azACz7dy3V5WK8TD1oPtlkthmfoFFLB5DZWAlbe4
XGvodfu1WeGTAUbM6mOjiKGU/gnD3qA75S3ifpAQF6/oCa9jCnOCv1xM1NG49BV5
+0NI7eTKBfTNPxOaMbJUTlFtvkCGubtLK+1H4tIwmC3VGSQp03e3wHRcwGji9aSq
BMf/hyCe0SWZdqD8myXp6FHU41AsAshdbf8CniEdAevw6ecYjVaPhDfYE7DxIvL7
F2A7aT7Zw48Xz9ULgV5tnfwO0szxn2OZJ0oUIPI1pZ2L9yQ0XhTkXZ5L6JNN/D+p
JnjbYdcRi/U8uKIiWzNffq5Q4/lBI3Yo23bY6jj3enKvOibIH+Q1I7M1U1pdHbfD
jzQQgrtXNNCJ6K4wnP2joLy1zVsJcRPI7flhaqT25mMbkSUnb7P2gKNDQcPbZo3G
ytRfyTsnCMoq91zM5zT9GRxQCJ2tU5gv3a4CUx/5Ph8h/zlfwKEodO3wa2+WR+la
cyRYbHHf2R2QHWIYWBkP7NAMzRELusWflsuITDyTmUdIpW9BKDv8QfuJBSFTqJRY
jDy5AX89ZjJsmFY35XWsuBI0Y0JlQCXWAt47qUDBmsGmM9/9qXe1KbgBPhnB1tBo
D02uYskkRQrmaquC8hRzBh2rPWKyR/kH41UZOa0/VGXp0IqCv+oX7qG2srkjdXR3
+ZMACy9Dtw8oqqsf6aJq0f0zYWFsCw4kL+dmBLcDOh8w6X4o9SbKPIgP4rjZ0bDJ
/xiLMcudl0JayrmyFtmKauNV5YPaceiGTuPRawdZeWGQ71RcHmK/75KvbKFHsTJE
1siS/I7yI6s/Q/kkwvRmCX7o
-----END PRIVATE KEY-----
`

const both_format_wrong_keys_rfc = `
-----BEGIN PRIVATE KEY-----
MIIP/gIBADALBglghkgBZQMEAxIEgg/qMIIP5gQgqvNwpdSfNgpA1GbuHR05ryiE
rByCEnViNhtxXs2N6qcEgg/A+BG8XK9ve/VLgotLZfSYLI8erMVgdRymekm5TW/G
Y4Pjbbcq4Xd0wqG263eFOjYG9bYWQHgXFo65+PL6hHS7rFHYDOPcWXTQ7zcGOdQz
+ZZeCG/j1sRT5+UpCU7KKHUel6MtMXoOdykJTKvMOJTpC7mPuFLlhNCixxbW5mj/
VSeBRHEIgDQBJRQCUAdVdyYlZhgIKCVydGRhNTJzVAU0AXVWgGOHdIVUMoA0g2IV
YFRxNkYzZhFGRkGBiGZhdncgU3ghQzgghTAGAlEFYlGGcUhiNgY1hXAwAmEzhSFl
dRZzglE1YmQCiEZDgVSABlAUOHJRUhNkcjAAEGFFNCM0UYYoRyRWMBB4YochOFZk
RRRQMGEYhENAZnEwY2UChxNWEGFgeEMzdEQAcyAxAyJgOEiINxQgFxiGACdlFzNY
dEAThmcwQBg1JQY3CDFAVXhgBIZgOCcmIiMzCBJhNUI0JFcQYQdUdGAGRmCEdyEx
VzUiRTUkUCByNhEWdBAIAUcRACVmRmRHUkCHU0RRJ4MAhnYXGDVEMYJwBjMCV4JS
EyIUE2ZgB3ZChVUYhXMiNHgDRGRiJiU0GGOIFVGFZBdDaEOIRzeCgIZ3hDKBQDFo
diQEhGJUhldTZDdxRGY4VmZkaFNhFHZzNzISMDhIBxaDFoAyc2hHR3cwAgd4VVQG
MgU0diAgeFQEVzCCU1MXBDYYIyBRF3BGBUYhQRdDE0BCiIBBJQRQCEZGcCdWIHFT
InAjVGRRVQczdHg0A0UHJ2N3MwgidYYYETFkY4Y0ElQxASAgMjFYNFcyNXU2ESAB
SDgYREEURUJ2QhAYMFYYFSJWQ2VSAlAlJTVYE1YoYhEoMDURhDRCYVUVNTAFIVdB
hkiGM0MlB3JAEhA0AVh0FBRhVUQYBwNUUEKDM2EUcYOEdDSAARI4RySAYkAoZggU
aERmgUeEQHSBVCdgADYwdAMnJQRUZhQzQSAFZESIAUMSNFACNIMXhhMVVYQTZCY1
BzYzJgBhdYGHY1ZGEWAUAyBlACQEdkdSM0FYYWJhgIgwKCAGSCVWIldyRjaBJlgh
F3NTcAdnRURABABAJ2RAYCcBZ3cVUTV3ZyZWEmRSF0ITBoYQZQBFOAAzJXdWgBdX
hDI2FQE4hVUwYQQYFiIwIHcVVwVjFVZhhwFlJYM3ZEUGZQZAVXEWEjRiVlNigoIU
QQgihwFDCGgnRIU1BQV0ZDAWF4QRYFQ2FSAQUEUQAYE1U0hmEDBDQzN1FVeFR4g3
BSM4UXQUhyAVQlg2IDEiRnAWMzRxJzERMoFwEGJ0BnQVWFhmUHI3aIGIhCVVQ1dV
dmgkAkIHaHUgGHUkNIU1CGQhg4ZGEnA1YgYDSFKENkQTUXVSR1dzKCJkATJFFGZF
III2VBAlZ4REIjR0coFjBzSBJERyE4RIFYhRQFAoEhM4BnghMzMWGDFiYFGEVQIm
g3RHQQIGVYhzZlYlMSd4QAKCR4YYBwBERWB1UxATEDAwYkgGQUVYImIEchYhd0JA
QTdiBIIRQwgXGFNmFSJoiDFIAYBwUwFTE4gBMgAgcxMiZ2VhOHIwgxRxRHdwcUZl
ciKFVzCGCAAEcTRoRxURRRN2ZlQDYmhWQlIIczFxJWBDdIdnIXOCglMjF1IgaHYi
YAFxJgaGCFZoaAeBKGE2RlNoV1aBA2EEEjRjdQdkV3JmcDMQM3I4NGFFACd1I2gD
gkIIIIIDFiQUGEJwAlZWBDdyUYFCCGcBJQIAEgQmJERSJlVnRxM0IwAHg3JUgwVi
GBJWQicjZ0V0WGJhIXeCBmdSIRRjiDBRiDEgNHVnADg1GECFFxMjVAMoNGMFEndE
SAhUBYRhADUoESN3Yld3UBA3MIczN1MBJUFiMldzcSVwJEM3IkhTMVUTOIGDNEBz
SGFgUiMlcDIQZyNnGEZ0BicWFAAwBgZhhlRwaIiERiVkJFJiE3d3KGczMhSCgUQi
cTZGJ1ZgNnN0JRR4JihVOEdncWNWU0E0hANiCEUmRxcYcWUGQXgQBUdQN4SEMxgU
goBYJAhBhIEEVGUXiCFRUWQyQ8Cp0UTanoTszvQIXLdKtl5jE45xfiHi52NPst3a
Dtgfo0AO9DQTv0Vy4VjhfuDw7BxaMpV2x5f6h8zAW67xPA3b8xJu8iyeCROyuuCu
Q5hWHcmHJcJJAH4N/dPgXDf2PjqanoGREGg1WvAm8SHzo3w6D5/H8y880RZVfp1C
dZOhkKPYeB4Jodb42mnYnxO56fMAtjTzfwQHKZvTRPHMCxx2qCPthC3Oj6xyT7mo
i6Da6L2R3HuiiTTfdPDciud5oK4v3FBozqEDGgxt9UjsMo4SbwWX5zfkQveV4M5C
9PAf1LwChJ5mLyBsTyPnIvuxo4vCGMn0+2+r790hwmRrZZwQExq1+NqAHLNp7djA
kM+2rZ8ymXF02MH4bit5zznkHGUctw8vn3j0LATNmS0mweG50mO1kV8zM3l+Wf7B
I9cMrx1nobFLFjNR4AZxJhmd9HF0rsLJV3q3+9LIS8KTgogDiye/p6tZVz18Z7ht
iJMnpptYjxIrFN2Eu8ms9U5IoBH9zTZAn129C7V/3r71ZSCYcW4R2DrsZRBhS/qh
0nINbwyfJTSydgfs/AfA9VAxCCce0v1DIxOLAwD2o5BVIIMZNYrLE+Nv8KndpDyt
v177BYrwd4Yv5E2wsIZMtdf/RXp0RMl0WZzsuMLzZPKvDWiYXHyrtvpfsAgchl11
mLj5Tk4gYHfnjT6T5OknseMIGH0bobnudmo+wA2PuYlbm3shFnK3+e4H64zB7Tst
sGKlV6Yo6D6C4ucg6nwhAKx0jKQPhTHc2v2xlEOPtBGXItkRuOYFXdnNnD/vnnzn
TcZkOnWONVFWurqP/2IBlFnKB4UKjN+w4DlcdAZ7Ni1cqh0aWqe7NqpJ26M+Hpqq
Vahq7KneRgjHHn30jGcJVQEYAo8yFI+frn3oMMb+CjHwb1tCl5hdoQBh2Cn/+LN/
IwPFTP6+cr/ihtIR+dM/lpWCd4M7MoUoSIehhBgr8XERBZz1fTngST5ceg0IBvdM
xTNx9qyo+Rc+aHTZxX1BSD/uvn+9mGWYF3KoWSY+UaifAwcAeevDSffncHfww8LH
UTAk2TfDALJEJDu3pF+55NWPwxuv4K4Nqi//WbBtxSmRebkub8hFl0F01Ct3X7q0
50DKYdAzm6n11ziFBDlu81eaP5gsa9eMSFm757Qu6PK+BcnalMTnx0BneKxM1xPD
Hq33tAGckRzBq2oCmlX95hI5xShaE/Sg+hIf6osF93/TFYvq9JiegERJaT6bfGIo
dAkKz7J2yLa4lOxhc2vfsYFMatI8YaLr7PGd/NETwl/OQLE34QwmBkSCmLZO2JQT
U4ngE6W8K4PMSTRMQ4TyOzmI8At0dcIzlHuXJ73rbkxp81KtH6urg0hWRCUk/PY3
nWhUWBP27NIzpWDPuk5X5QkdBU1r0/FAnUnJYpD7C0Hg2x2/RKX9pHeN5rEdZ2Ca
z0QGdDBNJm0CQR1ZQD1K2GWkXK5DIChY7OvNqhwG8RgAMX/yXQOQUm/l9B6pIapT
v0z3H7wRSb6iYBbsdVTVtkEj/dX5rMKxoWkYxwOePJj9Yvp1e24ezJA/n5DWai4t
sN89W2/o2xMG/av9i8md76DtTgjyGIvoZzFnolXF8AnTgDq6GMPaxr68MlgmaIcQ
FfIv70GqP0v3fYKXM8MwS3iBUvHZkPO2lTasPL9BG9aegv58cHnbVWv+7P17hiRx
VwX4AapO0SC1yeKYRbYaq1uG28C9Wr6crA3acEGnSjqMnaNII1BvFT2abDTNRcHM
9IOlmCiQlGHsM0oySAHq8yzBfR64v1IqaxESLcFVCtqqPYCCrnXBLtwDWd/IDlMP
e/aKLhIJBwiwf4muW+MN07Fm3Ajn6yYai2ZUR9nWntboDdxb3gLiOWPJy/1q43AD
DMUTnv/tASgFanUdMKczNl2sjXfWuNZXHkqP9wGdCW8wma3yMU75+bue/Vv+d6BM
+O24in7dXSXr3aSyhQvhPQd2TNMIOCmFQ30ueLJJJwlaK5bQaK1geEw6qvAkCwnY
d2JnVvsmvdJOv2ZK2eKBavui9UIpYm9Dc3bnwzJpVq73AmKV1Siu4gu9yOkNmo+a
g7Cio+bcy0/g+VUXLjI0U8dqVby+3ZwCCDHgGaxvLqZD5ZC091JzNMnVvrUSprad
DA66kuu63YudCw0c4Sp8Li8SeBk75XosMLzUchjcRwhsEG/6YK4E1wSlUhnqiLds
G0jvCxjM7xPDlFXIUT0JdcLyn4LgP6mayMUHdOTRNX0kc/7k3In1NVtgJLJsYPYO
c8WVXq2f6A20cE0IkfIRovxewk/L18Q8+hhFge6pM6h1OKkxfIVmQP7fUKptqAKX
GvhHvnTy0XSuxyfWScKMI3ElPkwvuN9HiZxyeLN3bcQrz2rilOhL79iAn1bWFCVs
RaE+UAbUabtinlR5FX4HAgks/QGqiNiBiRDWF9nTYU7QqqerTYF29chxGZb5dyNS
L2vtUht8TV0D3nmJVV+YH40/G5xtUpd2AUmefyZfCTZKWbGpMMoi7ZRRexxB64fE
/0vF7w0g81OtPlpP6Jl56ZFVF8gK6YYsChXH+PEsdHEuUjeaVVrAsvlXiwdym9GD
cvCfmNWCqezAbXK/ugzxUQKeDbU/w3l6BtQnRG2mXHkiAAn7TgZP2yMYyeUzD7RP
u48H/U1GgaydXWfiNhsbAWxQM/4hnP9OipAYK2HsVBY7wKDA3D+KYlMpgPZKpYGo
z3MQIMp7L0A4hlV5X6OMHTEoaaA9TnCglB0t3TszvR2TZ/pkJ4mtXdbme17otRnt
z2KLn9jGiTQl3QvM+cQ2FvwEhz/dGGrbV3MD2IR5FWsl1mCnzmm0sc7yTL6UhG1n
6/cBGgDwl+lRYAQdeX4pWtAGS8OdOE3pJu0v5631A5Rev+2jBE/OUlwDxuuwZ49K
42Z5bw12XXE1G6JeFHHdEa600mqAWzQg6I19SiPylvN66tZQfAesOnVUGAjd8RjM
B69/5U1+uNh4KLh+BeOfar3/wTo5zpnMbthH9WtTzAQiDsRVS4q+0mcHtuO2HsnF
eWqsRiuu/eSd6x7rgA1rbKDdkxAUpqCS70nXEMV7v6LkOhugPs5MyKzP0r45HPu9
6o2VSwmW3wgQ9qIHwBx+OBJxOe1673XCe6eZLdsngUW+NBSvnE3hQ8XZzBtn6FYP
+TVVp3g6/Z+rhYWq3SII+gn0jTQIBcN62JReZ5LL5KzhsI78IbD7ayM4tqkJr1uA
/5phviMZFfvgEcTLwMUdoL3yH/ryYkTKMwHfA16Gj1w1kFshurddf+biGSPGYMN5
iY1hJGzX2CQlCRYJG+QtkQ2i
-----END PRIVATE KEY-----
`
